version: "3"
services:
  chikuwabu_nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chikuwabu_web

  chikuwabu_web:
    build: ./web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src/:/var/www/html
      - ./web/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - chikuwabu_db

  chikuwabu_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chikuwabu_db
      MYSQL_USER: chikuwabu
      MYSQL_PASSWORD: chikuwabu3939ococ
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs/mysql/:/var/log/mysql/
    ports:
      - 3306:3306

  # chikuwabu_pma:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=petata_db
  #     - PMA_USER=petata
  #     - PMA_PASSWORD=petata
  #   depends_on:
  #     - petata_db
  #   ports:
  #     - 8080:80